### ISSUE TITLE
is php7.0 yet

### ISSUE THREAD

**Issue by tabago** [boekkooi/openshift-cartridge-php#8] opened 2015-12-13 08:15 UTC
php7.0 would like to install. 
I would like to know how .

**Comment by boekkooi** [comment] 2015-12-13 10:48
Hi @tabago, 
These is no PHP 7.0.0 support in this catridge (yet) the problem is that for PHP 7 to compile more then 512mb of RAM (https://github.com/boekkooi/openshift-cartridge-php/issues/7) is need and since I don't have a Medium gear on openshift I can't compile it.

If you do have a medium gear you can follow the instructions [Compiling a new version](https://github.com/boekkooi/openshift-cartridge-php#compiling-a-new-version). This will probably not work in total because there are some minor changes compiling PHP 7 but it's a good starting point.

If you get it to compile a PR would be very welcome.

**Comment by rscorer** [comment] 2016-01-02 09:52
hi @boekkooi, 
thanks for this repo :) 
i got 7.0.1 to compile in a medium gear, but i'm not clear on changes to make it work. its now in  a branch in my fork - apologies for the bad pull request!

**Comment by boekkooi** [comment] 2016-01-26 23:28
Closing this issue please follow PR #8

**Closed as completed by boekkooi** 2016-01-26 23:28 UTC
